name: macOS Runner

on:
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-15

    steps:
      - name: Cek macOS
        run: |
          sw_vers
          uname -a

      - name: Cek Xcode
        run: |
          xcodebuild -version

      - name: Cek Swift
        run: |
          swift --version
